### PR TITLE
Ng2LocationServices take account of APP_BASE_HREF.

### LINKED ISSUE #32: [beta.4][Ng2LocationServices] take account of APP_BASE_HREF
Ng2LocationServices doesn't take account of `APP_BASE_HREF` which produce `Maximum call stack size exceeded exception
```
<base href="/app/">
```
selection_064

### PR DESCRIPTION
**Pull request by aitboudad**
fixed #32
**Note**: I'm not sure if this is the right solution ;)

### CODE REVIEW

File: src/location/locationService.ts [hunk 1]
```diff
@@ -11,7 +11,8 @@ export class Ng2LocationServices extends BaseLocationServices {
   }
 
   _get() {
-    return this._locationStrategy.path(true);
+    return this._locationStrategy.path(true)
+      .replace(this._locationStrategy.getBaseHref().replace(/\/$/, ''), '');
```
Comment (christopherthielen) [inline src/location/locationService.ts]: it's unfortunate the location strategy class doesn't return the path without the base href.
It knows how to generate urls with the base href via `prepareExternalUrl`.

**Comment by christopherthielen** [comment]
Looks good! Thank you.
